---
title: "topic presentation"
date:  "2019/4/2"
output:
  pdf_document:
    fig_height: 6
    fig_width: 10
    latex_engine: xelatex
  word_document: default
  html_document:
    df_print: paged
CJKmainfont: Microsoft YaHei
zihao: 15
---
# 研究背景   
&emsp;&emsp;新冠肺炎自爆发以来，感染人数呈爆发式增长，就目前的情势来看，这次的疫情有可能演变成全球范围内的流行疾病，疫情已经从国内拓展至国外许多国家，而不同国家有着各自的发展态势，因此对比分析不同大陆病毒的传播特征将有利于找到最有利的防控条件。  

# 研究问题   
&emsp;&emsp;将主要几个国家所代表的疫情数据以洲的方式进行汇总，对比分析五大洲的疫情发展态势。    

# 数据来源   
&emsp;&emsp;JHU国家疫情数据      

# 研究方法  
&emsp;&emsp;首先通过阻滞增长模型预测各洲增长的基本态势，其次将会致力于构建新型冠状病毒肺炎疫情扩散的 SIR模型，并且对比SI、SIS、SIR、SEIR以及SEITR等动力学模型对此次疫情中的几种感染
情况进行仿真模拟研究，以传染概率、治愈率、移除率和消除率为基本参数，试图找出预防和控制肺炎疫情发生或蔓延的方法，最终找到一个最为合适的模型最为最终的预测模型。针对于不同的国家防控与否的举措，做出疫情扩散的仿真模拟研究，并根据实际疫情数据将不同的洲和国家做出聚类总结。     

# 问题与挑战      
&emsp;&emsp;1.由于这次疫情的复杂性，采用阻滞增长模型的精确度可能是有限的。 
&emsp;&emsp;2.用SIR模型进行建模很重要的一点是获得准确的模型参数，例如传染率、恢复率、移除率和消除率以及易感人群、感染人群和移除人群的初值的确定。   
&emsp;&emsp;3.SIR模型中没有考虑潜伏期，而此次新冠肺炎的潜伏期又相对较长，且不易察觉，所以潜伏期也是一个很重要的因素，因而考虑SEIR模型。   

# 解决办法   
&emsp;&emsp;查找相关文献，根据各个州爆发期初一段时间的数据用MCMC或者log-lingear或者其他的模型来合理的估计相关参数。  